---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-local
  namespace: argocd

  labels:
    environment: local
    purpose: sync
spec:
  project: default

  source:
    repoURL: git@github.com:CouchPartyGames/MultiplayerGameService.git
    path: argocd/local/infra
    targetRevision: HEAD

  destination:
    namespace: default
    name: in-cluster

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: games-local
  namespace: argocd

  labels:
    purpose: sync
    environment: local
spec:
  project: default

  source:
    repoURL: git@github.com:CouchPartyGames/MultiplayerGameService.git
    path: argocd/local/games
    targetRevision: HEAD

  destination:
    namespace: default
    name: in-cluster

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: games-orchestrator-local
  namespace: argocd

  labels:
    purpose: sync
    environment: local
spec:
  project: default

  source:
    repoURL: git@github.com:CouchPartyGames/MultiplayerGameService.git
    path: argocd/local/games-orchestrator
    targetRevision: HEAD

  destination:
    namespace: default
    name: in-cluster

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
