---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  labels:
    environment: local
    purpose: progressive-delivery
spec:
  project: infra

  source:
    chart: argo-rollouts
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.43.2

  destination:
    name: in-cluster
    namespace: argo-rollouts

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true

  revisionHistoryLimit: 3
