---
# https://cert-manager.io/docs/installation/helm/

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd

  labels:
    environment: local
    purpose: certificates

spec:
  project: infra

  sources:
    - repoURL: git@github.com:CouchPartyGames/MultiplayerGamesService.git
      targetRevision: main
      ref: myRepo
    - repoURL: https://charts.jetstack.io
      targetRevision: v1.14.4
      chart: cert-manager
      helm:
        valueFiles:
          - $myRepo/helm/external-values/local/infra/cert-manager-local.yaml

  destination:
    name: in-cluster
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true

  revisionHistoryLimit: 3
